PROGRAM POTENTIAL

    USE Public_Module		!VARIABLES
	use RootGrowth
    IMPLICIT NONE
 
!-----Formal parameters
      INTEGER       ITASK , IUNITD, IUNITL, CROPSTA, IDOY, I, K, NL
      LOGICAL       OUTPUT, TERMNL
      CHARACTER (128) FILEI1, FILEIT, FILEI2
      CHARACTER (32) ESTAB
      REAL    DOY , TIME, DELT  , LAT  , RDD, TRC, NFLV, NSLLV
      REAL    TMMN, TMMX, TMAXC, TMINC, TKLT  , ZRTMS, LRSTRS, LDSTRS, LESTRS, NRT
      REAL    PCEW, CPEW, DAE , LAIROL, ZRT  , DVS, RNSTRS, WCL(10), WL0, DLDR
      REAL    LAI, LLV  , SLA , WLVG  , WST  , WSO, GSO, GGR, GST, GLV, PLTR 
      REAL    TRW, TRWL(10), TKL(10)
!     FOR EXPERIMENT FILE 
      CHARACTER*(128) OUTPUTFILE
      INTEGER YRSIM, EDATE, PAGE,IRRCOD 
      CHARACTER*1, ISWWAT, ISWNIT, PLME,IIRRI
      REAL PLPH, PLYPOP, PLANTS, PLDP,IRRI, WL0MIN, KPAMIN, SLMIN, WLODAY
      REAL IRMTAB(300), RIRRIT(750),ISTAGET(900), TMCTB(750)
      
 !GENERATE EXPERIMENT FILE
      CALL ExperimentFileEdit(OUTPUTFILE, YRSIM, EDATE,& 
                ISWWAT, ISWNIT, PLME, PAGE, PLPH, PLYPOP,PLANTS, PLANTS, PLDP, &
                IIRRI, IRRCOD,IRMTAB, RIRRIT, IRRI, WL0MIN, KPAMIN, SLMIN, WLODAY, ISTAGET, TMCTB)
!     Used STRING
!   ESSENTIAL INFORMATION MUST BE PROVIDED FROM UPPER LAYER
!   FILEI1 = 'D:\...\...\IR72.CRP
!   FILEIT = 'D:\...\...\...\N150.exp
    TRW =TRC; OUTPUT = .FALSE.; PV%PROOT_NUTRIENT = .FALSE.; NL = PV%PNL
    FILEI2 = "";IUNITD = 30; IUNITL = 40
    DELT = 1.0  !TIME STEP IS 1.0
    DO I = 1, NL
        TKL(I) = PV%PDLAYER(I)/1000.0      !CONVERT SOIL LAYER THICKNESS FROM mm TO m
    END DO
!   ESSENTIAL INFORMATION    
    CALL WNOSTRESS (NL, TRW, TRWL, ZRT, TKL, LRSTRS, LDSTRS, LESTRS, PCEW, CPEW)

    CALL ORYZA1(ITASK,  IUNITD, IUNITL, FILEI1, FILEI2,FILEIT, &
                        OUTPUT, TERMNL, IDOY  , DOY, &
                        TIME,   DELT,   LAT,    RDD,    TMMN,   TMMX, &
                        NFLV,   NSLLV,  NRT,	RNSTRS,                 &
                        ESTAB,  TKLT,   ZRTMS,  CROPSTA, &
                        LRSTRS, LDSTRS, LESTRS, PCEW,  CPEW, TRC, &
                        DAE,    SLA, LAI,    LAIROL, ZRT,    DVS, &
                        LLV,    DLDR, WLVG, WST, WSO, GSO, GGR, GST, GLV, &
                        PLTR, WCL, WL0)
    CALL NNOSTRESS2(DELT, IUNITD, IUNITL, ITASK, FILEI1, FILEIT, &
                           CROPSTA, DVS, WLVG, LAI, SLA, NFLV, NSLLV, RNSTRS)

END PROGRAM POTENTIAL